name: "E2E Browserstack"
on:
  workflow_dispatch:
    inputs:
      app_version:
        description: "Enter the version of the mobile app you want to test from https://github.com/GaloyMoney/galoy-mobile/tags. For example, 2.0.58"
        required: true
env:
  APP_VERSION: ${{ github.event.inputs.app_version }}
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
  GALOY_TOKEN: ${{ secrets.GALOY_TOKEN }}
  GALOY_TOKEN_2: ${{ secrets.GALOY_TOKEN_2 }}
jobs:
  e2e-browserstack:
    name: E2E Browserstack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'GaloyMoney/galoy-mobile'
      - uses: actions/setup-node@v2
      - run: git fetch --all --tags
      - run: git checkout $APP_VERSION
      - run: yarn install
      - name: Run check code
        run: yarn check-code
      - name: Get the BROWSERSTACK_APP_ID from the API i.e bs://...
        run: |-
          BROWSERSTACK_APP_ID=$(curl -u "$BROWSERSTACK_USER:$BROWSERSTACK_ACCESS_KEY" \
            -X GET "https://api-cloud.browserstack.com/app-automate/recent_group_apps" |  \
            APP_VERSION=$APP_VERSION jq 'first( .[] | select( .app_version == env.APP_VERSION )) | .app_url') &&
          echo "BROWSERSTACK_APP_ID=$BROWSERSTACK_APP_ID" >> $GITHUB_ENV &&
          echo $BROWSERSTACK_APP_ID
      - name: Run E2E test on Browserstack
        run: BROWSERSTACK_BUILD="Android Manual Test" BROWSERSTACK_BUILD_VERSION="$APP_VERSION" BROWSERSTACK_APP_ID=${{env.BROWSERSTACK_APP_ID}} E2E_DEVICE="android" ./node_modules/.bin/wdio e2e/config/browserstack.conf.js
