name: "E2E Browserstack"
on:
  workflow_dispatch:
    inputs:
      app_version:
        description: "Enter the version of the mobile app you want to test from https://github.com/GaloyMoney/galoy-mobile/tags. For example, 2.0.58"
        required: true
env:
  APP_VERSION: ${{ github.event.inputs.app_version }}
jobs:
  e2e-browserstack:
    name: E2E Browserstack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'GaloyMoney/galoy-mobile'
      - uses: actions/setup-node@v2
      - run: git fetch --all --tags
      - run: git checkout $APP_VERSION
      - run: yarn install
      - name: Run check code
        run: yarn check-code
